name    'blendedbyus-stunnel'
version '1.1.0'
source 'https://github.com/BlendedByUs/blendedbyus-stunnel.git'
author 'BlendedByUs'
license 'Apache License, Version 2.0'
summary 'A module managing stunnel.'
description 'Derived from the original puppetlabs-stunnel here this version allows multiple service blocks that will allow multiple certificates to be run on a single port (multiple ip addresses) indirectly removing the need for running multiple stunnel instances. Please verify that your stunnel version supports this.'
project_page 'https://github.com/BlendedByUs/blendedbyus-stunnel'
