name    'blendedbyus-stunnel'
version '1.0.0'
source 'https://github.com/BlendedByUs/blendedbyus-stunnel.git'
author 'BlendedByUs'
license 'Apache License, Version 2.0'
summary 'A module for creating secure tunnels, specifically designed for https'
description 'Uses the stunnel application to setup SSL encrypted and authenticated tunnels.'
project_page 'https://github.com/BlendedByUs/blendedbyus-stunnel'
